// <auto-generated />
using System;
using GarageFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GarageFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GarageFlowDbContext))]
    [Migration("20260512005049_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarageFlow.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Executions.ExecutionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualTimeMinutes")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("actual_time_minutes");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MechanicId")
                        .HasColumnType("uuid")
                        .HasColumnName("mechanic_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_execution_orders_service_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_execution_orders_status");

                    b.ToTable("execution_orders", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Parts.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_parts_code");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_parts_sku");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Purchasing.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_supplier_by_employee_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_purchase_orders_status");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_orders_supplier_id");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.ServiceOrders.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("FrontDeskEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("front_desk_employee_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_service_orders_customer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_service_orders_status");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_service_orders_vehicle_id");

                    b.ToTable("service_orders", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Services.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_services_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_services_name");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Stock.SeparationOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmedByMechanicAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_by_mechanic_at");

                    b.Property<DateTime?>("ConfirmedByStockistAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_by_stockist_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExecutionOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_order_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("StockistId")
                        .HasColumnType("uuid")
                        .HasColumnName("stockist_id");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionOrderId")
                        .HasDatabaseName("ix_separation_orders_execution_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_separation_orders_status");

                    b.ToTable("separation_orders", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Stock.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AvailableQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("available_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<decimal>("MinimumQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("minimum_quantity");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("reserved_quantity");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ItemType", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_stocks_item_type_item_id");

                    b.ToTable("stocks", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Suppliers.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Supplies.Supply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseCost")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_cost");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PreferredSupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_supplier_id");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_supplies_code");

                    b.ToTable("supplies", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerId", "IsActive");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Infrastructure.Auth.AuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("auth_users", (string)null);
                });

            modelBuilder.Entity("GarageFlow.Domain.Customers.Customer", b =>
                {
                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("address_number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("cnpj");

                            b1.HasKey("CustomerId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("cnpj IS NOT NULL");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("CustomerId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("cpf IS NOT NULL");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("phone_number");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Cnpj");

                    b.Navigation("Cpf");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("GarageFlow.Domain.Employees.Employee", b =>
                {
                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("address_number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("cnpj");

                            b1.HasKey("EmployeeId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("cnpj IS NOT NULL");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("EmployeeId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("cpf IS NOT NULL");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("phone_number");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Cnpj");

                    b.Navigation("Cpf");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("GarageFlow.Domain.Purchasing.PurchaseOrder", b =>
                {
                    b.OwnsMany("GarageFlow.Domain.Purchasing.PurchaseItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("purchase_order_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ItemId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("item_id");

                            b1.Property<string>("ItemName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("item_name");

                            b1.Property<int>("ItemType")
                                .HasColumnType("integer")
                                .HasColumnName("item_type");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("UnitPrice")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("unit_price");

                            b1.HasKey("purchase_order_id", "ItemId");

                            b1.ToTable("purchase_order_items", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("purchase_order_id");
                        });

                    b.OwnsMany("GarageFlow.Domain.Purchasing.PurchaseOrderSeparationRef", "SeparationOrderRefs", b1 =>
                        {
                            b1.Property<Guid>("purchase_order_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SeparationOrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("separation_order_id");

                            b1.HasKey("purchase_order_id", "SeparationOrderId");

                            b1.ToTable("purchase_order_separation_refs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("purchase_order_id");
                        });

                    b.Navigation("Items");

                    b.Navigation("SeparationOrderRefs");
                });

            modelBuilder.Entity("GarageFlow.Domain.ServiceOrders.ServiceOrder", b =>
                {
                    b.OwnsOne("GarageFlow.Domain.ServiceOrders.Diagnostic", "Diagnostic", b1 =>
                        {
                            b1.Property<Guid>("ServiceOrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("service_order_id");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("Description")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("MechanicId")
                                .HasColumnType("uuid")
                                .HasColumnName("mechanic_id");

                            b1.Property<string>("SelectedServiceIds")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("[]")
                                .HasColumnName("selected_service_ids");

                            b1.Property<DateTime>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.HasKey("ServiceOrderId");

                            b1.HasIndex("Id")
                                .IsUnique()
                                .HasDatabaseName("ix_service_order_diagnostics_id");

                            b1.ToTable("service_order_diagnostics", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ServiceOrders.Quote", "Quote", b1 =>
                        {
                            b1.Property<Guid>("ServiceOrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("service_order_id");

                            b1.Property<DateTime?>("AcceptedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("accepted_at");

                            b1.Property<DateTime>("GeneratedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("generated_at");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("RejectedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("rejected_at");

                            b1.Property<string>("RejectionReason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("rejection_reason");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<decimal>("TotalAmount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_amount");

                            b1.HasKey("ServiceOrderId");

                            b1.HasIndex("Id")
                                .IsUnique()
                                .HasDatabaseName("ix_service_order_quotes_id");

                            b1.ToTable("service_order_quotes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ServiceOrderId");

                            b1.OwnsMany("GarageFlow.Domain.ServiceOrders.QuoteItem", "Items", b2 =>
                                {
                                    b2.Property<Guid>("service_order_id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<decimal>("LaborPrice")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("labor_price");

                                    b2.Property<decimal>("PartsTotal")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("parts_total");

                                    b2.Property<Guid>("ServiceId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("service_id");

                                    b2.Property<string>("ServiceName")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("service_name");

                                    b2.Property<decimal>("Subtotal")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("subtotal");

                                    b2.Property<decimal>("SuppliesTotal")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("supplies_total");

                                    b2.HasKey("service_order_id", "Id");

                                    b2.ToTable("service_order_quote_items", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("service_order_id");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsMany("GarageFlow.Domain.ServiceOrders.ServiceOrderServiceHistory", "ServiceHistory", b1 =>
                        {
                            b1.Property<Guid>("service_order_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Action")
                                .HasColumnType("integer")
                                .HasColumnName("action");

                            b1.Property<Guid>("ActorId")
                                .HasColumnType("uuid")
                                .HasColumnName("actor_id");

                            b1.Property<DateTime>("OccurredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("occurred_at");

                            b1.Property<string>("Reason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("reason");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("service_id");

                            b1.Property<int>("Source")
                                .HasColumnType("integer")
                                .HasColumnName("source");

                            b1.HasKey("service_order_id", "Id");

                            b1.ToTable("service_order_service_history", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("service_order_id");
                        });

                    b.OwnsMany("GarageFlow.Domain.ServiceOrders.ServiceOrderServiceItem", "Services", b1 =>
                        {
                            b1.Property<Guid>("service_order_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AddedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("added_at");

                            b1.Property<Guid>("AddedByActorId")
                                .HasColumnType("uuid")
                                .HasColumnName("added_by_actor_id");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<string>("RemovalReason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("removal_reason");

                            b1.Property<DateTime?>("RemovedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("removed_at");

                            b1.Property<Guid?>("RemovedByActorId")
                                .HasColumnType("uuid")
                                .HasColumnName("removed_by_actor_id");

                            b1.Property<Guid>("ServiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("service_id");

                            b1.Property<int>("Source")
                                .HasColumnType("integer")
                                .HasColumnName("source");

                            b1.HasKey("service_order_id", "Id");

                            b1.HasIndex("service_order_id", "ServiceId")
                                .IsUnique()
                                .HasDatabaseName("ux_service_order_services_active")
                                .HasFilter("\"is_active\" = true");

                            b1.ToTable("service_order_services", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("service_order_id");
                        });

                    b.Navigation("Diagnostic");

                    b.Navigation("Quote");

                    b.Navigation("ServiceHistory");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("GarageFlow.Domain.Services.Service", b =>
                {
                    b.OwnsMany("GarageFlow.Domain.Services.ServicePartItem", "Parts", b1 =>
                        {
                            b1.Property<Guid>("service_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PartId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("part_id");

                            b1.Property<string>("PartName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("part_name");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.HasKey("service_id", "PartId");

                            b1.HasIndex("service_id", "PartId")
                                .IsUnique()
                                .HasDatabaseName("ix_service_parts_service_id_part_id");

                            b1.ToTable("service_parts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("service_id");
                        });

                    b.OwnsMany("GarageFlow.Domain.Services.ServiceSupplyItem", "Supplies", b1 =>
                        {
                            b1.Property<Guid>("service_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SupplyId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("supply_id");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("quantity");

                            b1.Property<string>("SupplyName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("supply_name");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer")
                                .HasColumnName("unit");

                            b1.HasKey("service_id", "SupplyId");

                            b1.HasIndex("service_id", "SupplyId")
                                .IsUnique()
                                .HasDatabaseName("ix_service_supplies_service_id_supply_id");

                            b1.ToTable("service_supplies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("service_id");
                        });

                    b.Navigation("Parts");

                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("GarageFlow.Domain.Stock.SeparationOrder", b =>
                {
                    b.OwnsMany("GarageFlow.Domain.Stock.SeparationPartItem", "Parts", b1 =>
                        {
                            b1.Property<Guid>("separation_order_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PartId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("part_id");

                            b1.Property<bool>("IsReserved")
                                .HasColumnType("boolean")
                                .HasColumnName("is_reserved");

                            b1.Property<string>("PartName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("part_name");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.HasKey("separation_order_id", "PartId");

                            b1.ToTable("separation_order_parts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("separation_order_id");
                        });

                    b.OwnsMany("GarageFlow.Domain.Stock.SeparationSupplyItem", "Supplies", b1 =>
                        {
                            b1.Property<Guid>("separation_order_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SupplyId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("supply_id");

                            b1.Property<bool>("IsReserved")
                                .HasColumnType("boolean")
                                .HasColumnName("is_reserved");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("quantity");

                            b1.Property<string>("SupplyName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("supply_name");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer")
                                .HasColumnName("unit");

                            b1.HasKey("separation_order_id", "SupplyId");

                            b1.ToTable("separation_order_supplies", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("separation_order_id");
                        });

                    b.Navigation("Parts");

                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("GarageFlow.Domain.Stock.Stock", b =>
                {
                    b.OwnsMany("GarageFlow.Domain.Stock.StockOperation", "Operations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("PerformedBy")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("performed_by");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("quantity");

                            b1.Property<string>("Reason")
                                .HasMaxLength(400)
                                .HasColumnType("character varying(400)")
                                .HasColumnName("reason");

                            b1.Property<Guid?>("ReferenceId")
                                .HasColumnType("uuid")
                                .HasColumnName("reference_id");

                            b1.Property<string>("ReferenceType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("reference_type");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.Property<Guid>("stock_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("stock_id", "CreatedAt")
                                .HasDatabaseName("ix_stock_operations_stock_id_created_at");

                            b1.ToTable("stock_operations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("stock_id");
                        });

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("GarageFlow.Domain.Suppliers.Supplier", b =>
                {
                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("address_number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("cnpj");

                            b1.HasKey("SupplierId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("phone_number");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("GarageFlow.Domain.Vehicles.Vehicle", b =>
                {
                    b.OwnsOne("GarageFlow.Domain.ValueObjects.LicensePlate", "LicensePlate", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("license_plate");

                            b1.HasKey("VehicleId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("GarageFlow.Domain.ValueObjects.Renavam", "Renavam", b1 =>
                        {
                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("renavam");

                            b1.HasKey("VehicleId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.Navigation("LicensePlate")
                        .IsRequired();

                    b.Navigation("Renavam")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
