apiVersion: v1
kind: Secret
metadata:
  name: garageflow-secret
  namespace: garageflow
  labels:
    app.kubernetes.io/name: garageflow
    app.kubernetes.io/part-of: garageflow
type: Opaque
stringData:
  Jwt__SecretKey: "dev-only-secret-key-32-bytes-long!!"
  POSTGRES_DB: "garageflow"
  POSTGRES_USER: "garageflow"
  POSTGRES_PASSWORD: "garageflow"
